from enum import Enum

class EntityType(str, Enum):
    PERSON = "PERSON"
    PHONE = "PHONE"
    ACCOUNT = "ACCOUNT"
    LOCATION = "LOCATION"
    ORGANIZATION = "ORGANIZATION"
    VEHICLE = "VEHICLE"

class RelationshipType(str, Enum):
    CALLED = "CALLED"
    VISITED = "VISITED"
    TRANSFERRED = "TRANSFERRED"
    OWNED = "OWNED"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    MET = "MET"
    CO_LOCATED = "CO_LOCATED"
    USES = "USES"

class AnalyticalPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFORMATIONAL = "INFORMATIONAL"

class CaseStatus(str, Enum):
    ACTIVE = "ACTIVE"
    UNDER_REVIEW = "UNDER_REVIEW"
    ON_HOLD = "ON_HOLD"
    CRITICAL_LEAD = "CRITICAL_LEAD"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"

class CasePriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    ROUTINE = "ROUTINE"
    LOW = "LOW"

class PatternType(str, Enum):
    CROSS_COMMUNITY_BRIDGE = "CROSS_COMMUNITY_BRIDGE"
    DENSE_NETWORK_CLUSTER = "DENSE_NETWORK_CLUSTER"
    RAPID_RELATIONSHIP_EXPANSION = "RAPID_RELATIONSHIP_EXPANSION"
    TRANSACTION_ANOMALY = "TRANSACTION_ANOMALY"
    TEMPORAL_CORRELATION = "TEMPORAL_CORRELATION"
    HIGH_BETWEENNESS_ENTITY = "HIGH_BETWEENNESS_ENTITY"

class AlertSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class AlertStatus(str, Enum):
    NEW = "NEW"
    INVESTIGATING = "INVESTIGATING"
    REVIEWED = "REVIEWED"
    DISMISSED = "DISMISSED"

class UserRole(str, Enum):
    ADMIN = "ADMIN"
    INVESTIGATOR = "INVESTIGATOR"
    VIEWER = "VIEWER"

class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    CASE_CREATED = "CASE_CREATED"
    CASE_VIEWED = "CASE_VIEWED"
    DATA_UPLOADED = "DATA_UPLOADED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ENTITY_VIEWED = "ENTITY_VIEWED"
    ALERT_VIEWED = "ALERT_VIEWED"
    ALERT_STATUS_CHANGED = "ALERT_STATUS_CHANGED"
    NOTE_CREATED = "NOTE_CREATED"
    REPORT_GENERATED = "REPORT_GENERATED"
    DEMO_RESET = "DEMO_RESET"
