import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Printer, 
  Check, 
  X, 
  Sparkles, 
  CheckCircle2, 
  ArrowLeft, 
  Calendar, 
  Clock, 
  Download,
  Plus,
  ShieldCheck,
  Building2,
  Users,
  UserCheck,
  FileSpreadsheet,
  AlertTriangle,
  ClipboardList,
  Eye,
  Loader2,
  ExternalLink
} from 'lucide-react';
import { useInvestigation } from '../../context/InvestigationContext';
import { reportService, CaseReport, ReportConfig } from '../../services/reportService';
import { caseService } from '../../services/caseService';
import { Case } from '../../types';

export const ReportGenerator: React.FC = () => {
  const { activeCaseId, openEntityProfile } = useInvestigation();
  const [reports, setReports] = useState<CaseReport[]>([]);
  const [activeReport, setActiveReport] = useState<CaseReport | null>(null);
  const [viewMode, setViewMode] = useState<'list' | 'report'>('list');
  const [showGenerateModal, setShowGenerateModal] = useState<boolean>(false);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generationStep, setGenerationStep] = useState<string>('');

  // Generation modal state
  const [reportTitle, setReportTitle] = useState<string>('');
  const [reportType, setReportType] = useState<string>('Comprehensive Investigation Summary');
  const [configOptions, setConfigOptions] = useState({
    includeSummary: true,
    includeEntities: true,
    includeWitnesses: true,
    includeDocuments: true,
    includeEvidence: true,
    includeTimeline: true,
    includeNetwork: true,
    includeAlerts: true,
    includeActions: true,
    includeObservations: true,
    includeSources: true
  });

  const loadReports = () => {
    const list = reportService.getReportsByCase(activeCaseId);
    setReports(list);
    if (list.length > 0 && !activeReport) {
      setActiveReport(list[0]);
    }
  };

  useEffect(() => {
    loadReports();
  }, [activeCaseId]);

  const handleGenerateSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsGenerating(true);

    const steps = [
      'Collecting current case records...',
      'Compiling witness statements & depositions...',
      'Indexing registered evidence & SHA-256 seals...',
      'Building chronological timeline summary...',
      'Analyzing graph topology & cross-community leads...',
      'Finalizing confidential report...'
    ];

    for (let i = 0; i < steps.length; i++) {
      setGenerationStep(steps[i]);
      await new Promise(r => setTimeout(r, 250));
    }

    const config: ReportConfig = {
      caseId: activeCaseId,
      reportType,
      reportTitle: reportTitle || `${reportType} — ${activeCaseId}`,
      ...configOptions
    };

    const newReport = await reportService.generateCaseReport(activeCaseId, config);
    loadReports();
    setActiveReport(newReport);
    setIsGenerating(false);
    setShowGenerateModal(false);
    setViewMode('report');
  };

  const handleDownload = (report: CaseReport) => {
    let content = `# TRACENET INVESTIGATION REPORT\n`;
    content += `CONFIDENTIAL LAW ENFORCEMENT INTELLIGENCE\n\n`;
    content += `REPORT ID: ${report.id} (Version ${report.version})\n`;
    content += `CASE: ${report.caseId} — ${report.caseTitle}\n`;
    content += `TYPE: ${report.reportType}\n`;
    content += `GENERATED BY: ${report.createdBy} (${report.badgeNumber})\n`;
    content += `TIMESTAMP: ${report.createdDate} ${report.createdTime}\n\n`;
    content += `==================================================\n`;
    content += `EXECUTIVE SUMMARY\n`;
    content += `==================================================\n`;
    content += `${report.executiveSummary}\n\n`;

    if (report.incident) {
      content += `==================================================\n`;
      content += `1. INCIDENT DETAILS\n`;
      content += `==================================================\n`;
      content += `FIR Number: ${report.incident.firNumber}\n`;
      content += `Type: ${report.incident.incidentType}\n`;
      content += `Date/Time: ${report.incident.date} ${report.incident.time}\n`;
      content += `Location: ${report.incident.location}\n`;
      content += `Description: ${report.incident.description}\n\n`;
    }

    if (report.witnesses.length > 0) {
      content += `==================================================\n`;
      content += `2. WITNESS STATEMENTS (Section 161 CrPC)\n`;
      content += `==================================================\n`;
      report.witnesses.forEach(w => {
        content += `- Witness: ${w.name} (${w.id}) | Age: ${w.age} | ${w.relationshipToIncident}\n`;
        w.statements.forEach(st => {
          content += `  * Statement #${st.statementNumber} (${st.date}): ${st.summary}\n`;
        });
      });
      content += `\n`;
    }

    if (report.evidence.length > 0) {
      content += `==================================================\n`;
      content += `3. REGISTERED DIGITAL EVIDENCE\n`;
      content += `==================================================\n`;
      report.evidence.forEach(ev => {
        content += `- [${ev.id}] ${ev.title} (${ev.policeStation}) | SHA-256: ${ev.digitalDocument?.integrityHash || (ev.hasDigitalCopy ? 'DIGITAL_ATTACHED' : 'PHYSICAL_REGISTERED')}\n`;
      });
      content += `\n`;
    }

    content += `==================================================\n`;
    content += `DISCLAIMER\n`;
    content += `==================================================\n`;
    content += `${report.disclaimer}\n`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.id}_${report.caseId}_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // VIEW MODE 1: REPORT DOSSIER PREVIEW
  if (viewMode === 'report' && activeReport) {
    return (
      <div className="max-w-5xl mx-auto space-y-6 select-none animate-in fade-in py-2">
        
        {/* Top Action Bar */}
        <div className="flex items-center justify-between print:hidden">
          <button
            onClick={() => setViewMode('list')}
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Back to Reports Directory ({reports.length})</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowGenerateModal(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition-all shadow-md"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Generate New Version</span>
            </button>
            <button
              onClick={() => handleDownload(activeReport)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download (.txt)</span>
            </button>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
          </div>
        </div>

        {/* Formal Printable Intelligence Dossier */}
        <div className="intel-card p-8 border border-slate-800 bg-[#090f1d] shadow-2xl space-y-7 print:p-0 print:border-none print:bg-white print:text-black">
          
          {/* Official Document Header */}
          <div className="border-b border-slate-800 pb-5 flex flex-col sm:flex-row sm:items-start justify-between gap-4">
            <div className="space-y-1">
              <span className="px-2.5 py-0.5 rounded bg-blue-500/20 text-blue-300 border border-blue-500/30 text-[10px] font-bold uppercase tracking-wider">
                CONFIDENTIAL // LAW ENFORCEMENT INTELLIGENCE
              </span>
              <div className="font-mono text-sm font-bold text-blue-400">TraceNet</div>
              <h2 className="text-xl font-bold text-white tracking-tight">
                {activeReport.title}
              </h2>
              <div className="text-xs text-slate-400 font-semibold uppercase tracking-wider">
                {activeReport.reportType} • Version {activeReport.version}.0
              </div>
              <p className="text-xs text-slate-300 pt-1">
                CASE IDENTIFIER: <strong className="text-blue-400 font-mono">{activeReport.caseId}</strong>
              </p>
            </div>

            <div className="text-right text-xs space-y-1 text-slate-400 font-mono">
              <div>Report ID: <strong className="text-white">{activeReport.id}</strong></div>
              <div>Investigator: <strong className="text-white">{activeReport.createdBy}</strong></div>
              <div>Badge: <strong className="text-slate-300">{activeReport.badgeNumber}</strong></div>
              <div>Generated: {activeReport.createdDate} • {activeReport.createdTime}</div>
            </div>
          </div>

          {/* Executive Summary */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
              Executive Summary
            </h4>
            <p className="text-xs text-slate-200 leading-relaxed font-sans bg-slate-950 p-4 rounded-lg border border-slate-800/80">
              {activeReport.executiveSummary}
            </p>
          </div>

          {/* Section 1: Incident Summary */}
          {activeReport.incident && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
                1. Incident Dossier & Statutory Filings
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                <div className="p-3 rounded-lg bg-[#090e1a] border border-slate-800 space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold block">FIR Number & Station</span>
                  <span className="text-white font-medium">{activeReport.incident.firNumber} ({activeReport.incident.policeStation})</span>
                </div>
                <div className="p-3 rounded-lg bg-[#090e1a] border border-slate-800 space-y-1">
                  <span className="text-[10px] text-slate-500 uppercase font-bold block">Incident Location & Date</span>
                  <span className="text-white font-medium">{activeReport.incident.location} • {activeReport.incident.date}</span>
                </div>
              </div>
              <p className="text-xs text-slate-300 leading-relaxed font-sans bg-[#090e1a] p-3 rounded-lg border border-slate-800">
                {activeReport.incident.description}
              </p>
            </div>
          )}

          {/* Section 2: Case Participants */}
          {activeReport.participants.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
                2. Case Participants Directory (Neutral Classifications)
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2.5 text-xs">
                {activeReport.participants.map(p => (
                  <div key={p.id} className="p-3 rounded-lg bg-[#090e1a] border border-slate-800 space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-white">{p.name}</span>
                      <span className="text-[9px] font-mono font-bold px-1.5 py-0.2 rounded bg-slate-900 text-slate-300 border border-slate-700">
                        {p.role.replace(/_/g, ' ')}
                      </span>
                    </div>
                    <div className="text-[11px] text-slate-400">{p.roleDescription}</div>
                    <div className="text-[10px] text-slate-500 font-mono truncate">{p.relevance}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 3: Witnesses & Statements */}
          {activeReport.witnesses.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
                3. Recorded Witness Depositions (Section 161 CrPC)
              </h4>
              <div className="space-y-2 text-xs">
                {activeReport.witnesses.map(w => (
                  <div key={w.id} className="p-3.5 rounded-lg bg-[#090e1a] border border-slate-800 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-white">{w.name} ({w.id})</span>
                      <span className="text-slate-400 font-mono text-[10px]">{w.relationshipToIncident}</span>
                    </div>
                    {w.statements.map(st => (
                      <div key={st.id} className="p-2.5 rounded bg-slate-950 border border-slate-800 text-[11px] space-y-1">
                        <div className="flex items-center justify-between text-slate-400 font-mono text-[10px]">
                          <span>Statement #{st.statementNumber} ({st.type})</span>
                          <span>{st.date} • {st.time}</span>
                        </div>
                        <p className="text-slate-200 font-sans">{st.summary}</p>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 4: Registered Evidence */}
          {activeReport.evidence.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
                4. Registered Digital Evidence & Bitwise Integrity
              </h4>
              <div className="space-y-1.5 text-xs">
                {activeReport.evidence.map(ev => (
                  <div key={ev.id} className="p-2.5 rounded bg-[#090e1a] border border-slate-800 flex items-center justify-between">
                    <div>
                      <span className="font-mono text-blue-400 font-bold">{ev.id}: </span>
                      <span className="text-white font-medium">{ev.title}</span>
                      <span className="text-slate-500 font-mono text-[10px] ml-2">({ev.policeStation})</span>
                    </div>
                    <span className="text-emerald-400 font-mono text-[11px] shrink-0">
                      {ev.hasDigitalCopy ? 'SHA-256 Verified' : 'Registered in Ledger'}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 5: Network Analytical Leads */}
          <div className="space-y-2">
            <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
              5. Network Topology & Graph Analytical Leads
            </h4>
            <div className="space-y-2 text-xs">
              {activeReport.networkSummary.bridgeLeads.map((lead, idx) => (
                <div key={idx} className="p-2.5 rounded bg-[#090e1a] border border-slate-800 flex items-center gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-amber-400 shrink-0" />
                  <span className="text-slate-200 font-sans">{lead}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section 6: Officer Field Observations */}
          {activeReport.observations.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-blue-400 border-b border-slate-800 pb-1">
                6. Officer Field Observations (Human Verified)
              </h4>
              <div className="space-y-2 text-xs">
                {activeReport.observations.map(obs => (
                  <div key={obs.id} className="p-3 rounded bg-[#090e1a] border border-slate-800 space-y-1">
                    <div className="flex items-center justify-between text-[10px] text-slate-400 font-mono">
                      <span>{obs.officer} ({obs.badge})</span>
                      <span>{obs.date} • {obs.time}</span>
                    </div>
                    <p className="text-slate-200 font-sans">{obs.observation}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Statutory Disclaimer */}
          <div className="pt-4 border-t border-slate-800 text-[11px] text-slate-400 italic bg-slate-950 p-4 rounded-lg border border-slate-800">
            <strong>STATUTORY NOTICE:</strong> {activeReport.disclaimer}
          </div>

        </div>

      </div>
    );
  }

  // VIEW MODE 2: REPORTS LIST DASHBOARD
  return (
    <div className="max-w-6xl mx-auto py-1 space-y-5 select-none animate-in fade-in">
      
      {/* Header Bar */}
      <div className="intel-card p-5 border border-slate-800 rounded-xl bg-[#0d1527] flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-xl">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            <span className="font-mono text-xs font-bold text-blue-400">{activeCaseId}</span>
            <span className="text-slate-600">•</span>
            <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-slate-400">
              INTELLIGENCE BRIEFINGS
            </span>
          </div>
          <h1 className="text-xl font-bold text-white tracking-tight">
            Case Intelligence Reports & Briefings ({reports.length})
          </h1>
          <p className="text-xs text-slate-400">
            Formally compiled investigation dossiers referencing all case records, witness statements, and registered evidence.
          </p>
        </div>

        <button
          onClick={() => setShowGenerateModal(true)}
          className="flex items-center gap-1.5 px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition-all shadow-md shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>Generate Case Report</span>
        </button>
      </div>

      {/* Reports Cards / Table */}
      {reports.length === 0 ? (
        <div className="intel-card p-12 border border-slate-800 rounded-xl bg-[#0c1322] text-center space-y-2">
          <FileText className="w-8 h-8 text-slate-600 mx-auto" />
          <h3 className="text-sm font-bold text-white">No Reports Generated</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto">
            No intelligence briefings have been compiled for {activeCaseId} yet.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.map((rpt) => (
            <div
              key={rpt.id}
              className="intel-card p-5 border border-slate-800 rounded-xl bg-[#0c1322] hover:border-slate-700 transition-all space-y-3.5 shadow-lg flex flex-col justify-between"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-blue-400">{rpt.id}</span>
                  <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-500/15 text-emerald-300 border border-emerald-500/30">
                    Version {rpt.version}.0 • {rpt.status}
                  </span>
                </div>

                <h3 className="text-sm font-bold text-white">{rpt.title}</h3>
                <div className="text-xs text-slate-400">{rpt.reportType}</div>
                <p className="text-xs text-slate-300 line-clamp-2 leading-relaxed font-sans">
                  {rpt.executiveSummary}
                </p>
              </div>

              <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-xs">
                <div className="text-[11px] text-slate-500 font-mono">
                  {rpt.createdDate} • {rpt.createdBy}
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={() => {
                      setActiveReport(rpt);
                      setViewMode('report');
                    }}
                    className="px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center gap-1 transition-colors"
                  >
                    <Eye className="w-3 h-3" />
                    <span>View Dossier</span>
                  </button>
                  <button
                    onClick={() => handleDownload(rpt)}
                    className="p-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 transition-colors"
                    title="Download Report"
                  >
                    <Download className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Modal: Generate Case Report */}
      {showGenerateModal && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 select-none animate-in fade-in">
          <div 
            className="w-full max-w-lg intel-card rounded-xl border border-slate-700 bg-[#0c1322] shadow-2xl p-5 space-y-4"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div>
                <span className="font-mono text-xs font-bold text-blue-400">{activeCaseId}</span>
                <h3 className="font-bold text-sm text-white">Generate Official Case Report</h3>
              </div>
              <button 
                onClick={() => setShowGenerateModal(false)}
                className="text-slate-400 hover:text-white"
              >
                ✕
              </button>
            </div>

            {isGenerating ? (
              <div className="py-8 text-center space-y-3">
                <Loader2 className="w-8 h-8 text-blue-400 animate-spin mx-auto" />
                <div className="font-bold text-white text-sm">{generationStep}</div>
                <div className="text-xs text-slate-400">Compiling multi-source investigation ledger...</div>
              </div>
            ) : (
              <form onSubmit={handleGenerateSubmit} className="space-y-3.5 text-xs">
                <div className="space-y-1">
                  <label className="block text-[10px] uppercase font-bold text-slate-400">Report Title</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. Operation Meridian Comprehensive Case Summary"
                    value={reportTitle}
                    onChange={(e) => setReportTitle(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-xs text-white focus:outline-none focus:border-blue-500"
                  />
                </div>

                <div className="space-y-1">
                  <label className="block text-[10px] uppercase font-bold text-slate-400">Report Type</label>
                  <select
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value)}
                    className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-xs text-white focus:outline-none focus:border-blue-500"
                  >
                    <option value="Comprehensive Investigation Summary">Comprehensive Investigation Summary</option>
                    <option value="Evidentiary Court Deposition Briefing">Evidentiary Court Deposition Briefing</option>
                    <option value="Inter-Agency Operational Briefing">Inter-Agency Operational Briefing</option>
                  </select>
                </div>

                <div className="space-y-2 pt-1 border-t border-slate-800">
                  <span className="block text-[10px] uppercase font-bold text-slate-400">Include Sections:</span>
                  <div className="grid grid-cols-2 gap-2 text-[11px] text-slate-300">
                    {Object.entries(configOptions).map(([key, val]) => (
                      <label key={key} className="flex items-center gap-2 cursor-pointer">
                        <input
                          type="checkbox"
                          checked={val}
                          onChange={() => setConfigOptions(prev => ({ ...prev, [key]: !val }))}
                          className="rounded bg-slate-900 border-slate-700 text-blue-600 focus:ring-0"
                        />
                        <span>{key.replace('include', '')}</span>
                      </label>
                    ))}
                  </div>
                </div>

                <div className="flex justify-end gap-2 pt-3 border-t border-slate-800">
                  <button
                    type="button"
                    onClick={() => setShowGenerateModal(false)}
                    className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-md"
                  >
                    Generate Report
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}

    </div>
  );
};
